#开发者专用，参数不要修改
Title="user.p.developer."
# TestNet=true

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.para.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 30
# 最多保存的历史日志文件个数
maxBackups = 10
# 最多保存的历史日志消息（单位：天）
maxAge = 9 
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="paradatadir"
dbCache=64
isStrongConsistency=true
singleMode=true
batchsync=false
isRecordBlockSequence=false
isParaChain = true

[p2p]
seeds=[]
enable=false
isSeed=false
serverStart=true
innerSeedEnable=true
useGithub=true
innerBounds=300
msgCacheSize=10240
driver="leveldb"
dbPath="paradatadir/addrbook"
dbCache=4
grpcLogFile="grpc33.log"

[rpc]
jrpcBindAddr=":8801"
grpcBindAddr=":8802"
whitelist=["*"]
jrpcFuncWhitelist=["*"]
grpcFuncWhitelist=["*"]
mainnetJrpcAddr="http://139.219.1.47:8801"

[mempool]
name="timeline"
poolCacheSize=10240
minTxFee=100000

[consensus]
name="para"
minerstart=false
#此处IP改成实际的地址
ParaRemoteGrpcClient = "139.219.1.47:8802"
#指定从主链某高度的区块开始同步
startHeight=1310000
#打包时间间隔，单位秒
writeBlockSeconds=2
#主链每隔几个没有相关交易的区块，平行链上打包空区块
emptyBlockInterval=50
#等待平行链共识消息在主链上链并成功的块数，超出会重发共识消息，最小是2
waitBlocks4CommitMsg=2
genesis="1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs"

[store]
name="mavl"
driver="leveldb"
dbPath="paradatadir/mavltree"
dbCache=128

[wallet]
minFee=100000
driver="leveldb"
dbPath="parawallet"
dbCache=16
signType="secp256k1"
minerdisable=true

[exec]
isFree=true
minExecFee=100000
enableStat=false

[exec.sub.manage]
superManager=[
    "1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs",
]

[exec.sub.token]
saveTokenTxList=true
tokenApprs = [
        "1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs",
]

[pprof]
listenAddr = "localhost:6061"